DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FOLLOWER;
CREATE TABLE USER (
  USER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_NAME VARCHAR(250) NOT NULL,
  USER_GUID VARCHAR(250) NOT NULL
);

CREATE TABLE FOLLOWER (
  FOLLOWER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(250),
  USER_NAME VARCHAR(250) NOT NULL
);